export const EXPENSE_REQUEST = "EXPENSE_REQUEST";
export const EXPENSE_FAILURE = "EXPENSE_FAILURE";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";

// POST
export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";   
export const ADD_EXPENSE_FAILURE = "ADD_EXPENSE_FAILURE";

// GET
export const GET_EXPENSES = "GET_EXPENSES";

// DELETE
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILURE = "DELETE_EXPENSE_FAILURE";